name: Codecov

on: workflow_call

jobs:
  Codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: ./coverage/
      - run: ls -R
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
