name: Deployment
on:
  release:
    types: [created]

jobs:
  npm:
    uses: ./.github/workflows/publish-npm.yml
    secrets:
      PUBLISH_NPM_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
  gpr:
    uses: ./.github/workflows/publish-gpr.yml
    secrets:
      PUBLISH_GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
